version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
